const fs = require("fs");
const readline = require("readline/promises");

async function runWizard() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  console.log("==========================================");
  console.log("Welcome to the Daraja M-Pesa Setup");
  console.log("==========================================\n");
  console.log(
    "Let's get your M-Pesa engine running. You can find these details on the Safaricom Daraja portal.\n",
  );
  try {
    const consumerKey = await rl.question("1. Paste your Consumer Key: ");
    const consumerSecret = await rl.question("2. Paste your Consumer Secret: ");
    const passkey =
      (await rl.question(
        "3. Paste your Passkey (or press Enter for Sandbox default): ",
      )) || "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919";
    const shortcode =
      (await rl.question(
        "4. Enter your Shortcode (or press Enter for 174379): ",
      )) || "174379";

    const envContent = `
        # Automatically generated bySetup Wizard
DARAJA_CONSUMER_KEY=${consumerKey.trim()}
DARAJA_CONSUMER_SECRET=${consumerSecret.trim()}
DARAJA_PASSKEY=${passkey.trim()}
DARAJA_SHORTCODE=${shortcode.trim()}
DARAJA_BASE_URL=https://sandbox.safaricom.co.ke
APP_API_KEY=${apiKey.trim()}
SERVER_PORT=8080
        `.trim();

    fs.writeFileSync("../.env", envContent);
    console.log("\n.env file created successfully!");
  } catch (error) {
    console.error("❌ Setup failed:", error);
  } finally {
    rl.close();
  }
}

runWizard();
